name: Build and deploy website

on:
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node 22.12
              uses: actions/setup-node@v4
              with:
                  node-version: "22.12.0"
            - name: Building the 'core' package
              working-directory: ./packages/core
              run: |
                  npm ci
                  npx svelte-package
            - name: Build the website
              working-directory: ./docs
              run: |
                  npm ci
                  npm run build
            - name: Upload static files as artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./docs/build
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
