name: Test and publish

on:
    release:
        types: [published]

permissions:
    contents: read
    id-token: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node 22.12
              uses: actions/setup-node@v4
              with:
                  node-version: "22.12.0"
            - name: Test the 'core' package
              working-directory: ./packages/core
              run: |
                  npm install
                  npm test

    publish-npm:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node 22.12
              uses: actions/setup-node@v4
              with:
                  node-version: "22.12.0"
                  registry-url: https://registry.npmjs.org/
            - name: Publish the 'core' package
              working-directory: ./packages/core
              run: |
                  npm install
                  npm publish --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
