name: Test the core package

on:
    push:
        branches:
            - "**"
    workflow_dispatch:

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node 22.12.0
              uses: actions/setup-node@v4
              with:
                  node-version: "22.12.0"
            - name: Test the 'core' package
              working-directory: ./packages/core
              run: |
                  npm install
                  npm test
